const paragraphs = [
  "Numerous birds were living on a mango tree in a forest. They were happy in their little nest. Before the rains begin, all the animals in the forest make their homes. Birds also made their homes safer and more secure. Many birds brought branches and leaves,",
  "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum,",
  "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here,",
  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  "Beloved, do not be sad. We currently have a guest. This male is trembling and starving. He needs your help.Hearing this, the companion fled with the dried branches. She set fire to the bird catcher. Then she took one look at the bird catcher and said, you are our guest,",
  "There was a crow living there. One day he was starving. The day before, he had not received any food. If I don't get anything to eat, I will starve to death, he thought. While the crow was looking for food, he saw a piece of bread. He immediately knocked it down, picked it up",
  "A bad Brahmin dealt with his family in a small house long ago. His followers will surely help him with food as well as clothing. Somehow managed to get the day off. One day, a Brahmin received 2 calf bones as a gift from one of his disciples. He was satisfied.",
  "Long ago, there was a Baja on the top of a hill. At the foot of the capital was a banyan tree on which crows used to sit every day. The crow was foolish. He wanted to imitate everyone. The capitalist Baja flew down every day in search of food.",
  "Let's come here tomorrow with your angling net, said one of them. I'm shocked we haven't seen this place before! Various other exclamations were removed.The crocodile heard it all. As the anglers left, he slowly climbed into the fish pond and headed straight for the fish.",
];
